// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgprgDxjw76D-vx9z1injCQDqxKDUdLKY',
    appId: '1:222293724613:web:1928a9aa06e30ebadb4fac',
    messagingSenderId: '222293724613',
    projectId: 'fitness-b6594',
    authDomain: 'fitness-b6594.firebaseapp.com',
    storageBucket: 'fitness-b6594.appspot.com',
    measurementId: 'G-QT1V0CFBF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZmYg0OaSpDEjHZPzO5Co2L0I5B4mdj4',
    appId: '1:222293724613:android:8a0e479f81916cccdb4fac',
    messagingSenderId: '222293724613',
    projectId: 'fitness-b6594',
    storageBucket: 'fitness-b6594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPm0nRGRk-8ydH_j3qdpnu4B2b3TMZu2o',
    appId: '1:222293724613:ios:73a7d7c0c606841adb4fac',
    messagingSenderId: '222293724613',
    projectId: 'fitness-b6594',
    storageBucket: 'fitness-b6594.appspot.com',
    iosBundleId: 'com.example.idcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPm0nRGRk-8ydH_j3qdpnu4B2b3TMZu2o',
    appId: '1:222293724613:ios:73a7d7c0c606841adb4fac',
    messagingSenderId: '222293724613',
    projectId: 'fitness-b6594',
    storageBucket: 'fitness-b6594.appspot.com',
    iosBundleId: 'com.example.idcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgprgDxjw76D-vx9z1injCQDqxKDUdLKY',
    appId: '1:222293724613:web:388c1748c3606217db4fac',
    messagingSenderId: '222293724613',
    projectId: 'fitness-b6594',
    authDomain: 'fitness-b6594.firebaseapp.com',
    storageBucket: 'fitness-b6594.appspot.com',
    measurementId: 'G-RB7JGZ4P8H',
  );
}
